MAIN += $(MYPATH)/start/initial.c

ifeq ($(EJECUTION),SPROFILE)
	MAIN += $(MYPATH)/src/io/input/SPROFILE/input.c
endif
ifeq ($(EJECUTION),FPROFILE)
	MAIN += $(MYPATH)/src/io/input/FPROFILE/input.c
endif
