ifeq ($(SOLVER),RK4)
	MAIN += $(MYPATH)/src/integration/methods/rk4.c
endif
ifeq ($(SOLVER),RK3)
	MAIN += $(MYPATH)/src/integration/methods/rk3.c
endif
ifeq ($(SOLVER),RK2)
	MAIN += $(MYPATH)/src/integration/methods/rk2.c
endif
