#dep: conv.c ../integration/solver.c main.h
#	gcc -I../dep conv.c ../integration/solver.c -o dep -lm
ttest: conv.c ../integration/solver.c main.h
	gcc -I../deb conv.c ../integration/solver.c -o ttest -lm
