massradius: main.c ../integration/solver.c ../integration/bisection.c ../ec_edo/polytropic.c ../regime/tov.c ../libs/main.h ../libs/user.h
	gcc -I ../libs main.c ../integration/solver.c ../integration/bisection.c ../ec_edo/polytropic.c ../regime/tov.c -o massradius -lm
